function ResultListCtrl($scope) {
  $scope.Results = [
    {"name": "Jim Vuti",
     "age": "25",
     "gender": "male",
     "location": "Congo",
     "pic": "images/male.png"},
    {"name": "Kathleen Cheche",
     "age": "29",
     "gender": "female",
     "location": "Congo",
     "pic": "images/female.png"},
    {"name": "Asad Haji",
     "age": "15",
     "gender": "female",
     "location": "Somalia",
     "pic": "images/female.png"},
    {"name": "Victor Nguesso",
     "age": "40",
     "gender": "male",
     "location": "Congo",
     "pic": "images/male.png"},
    {"name": "Ahmed Khalifa",
     "age": "33",
     "gender": "male",
     "location": "Somalia",
     "pic": "images/male.png"},
    {"name": "Hamisi",
     "age": "15",
     "gender": "female",
     "location": "Somalia",
     "pic": "images/female.png"},
    {"name": "Akong",
     "age": "17",
     "gender": "female",
     "location": "South Sudan",
     "pic": "images/female.png"},
    {"name": "Okot Qasim",
     "age": "35",
     "gender": "male",
     "location": "South Sudan",
     "pic": "images/male.png"},
    {"name": "Abdel Aziz",
     "age": "27",
     "gender": "male",
     "location": "South Sudan",
     "pic": "images/male.png"},
    {"name": "Zeinab Badawi",
     "age": "22",
     "gender": "female",
     "location": "South Sudan",
     "pic": "images/female.png"},
    {"name": "Farid Akram",
     "age": "20",
     "gender": "male",
     "location": "Syria",
     "pic": "images/male.png"},
    {"name": "Amira Anwar",
     "age": "35",
     "gender": "female",
     "location": "Syria",
     "pic": "images/female.png"},
    {"name": "Belcha",
     "age": "25",
     "gender": "female",
     "location": "Congo",
     "pic": "images/female.png"},
    {"name": "Keicha Makemba",
     "age": "37",
     "gender": "female",
     "location": "Congo",
     "pic": "images/female.png"},
    {"name": "Archange Ruhadusha",
     "age": "45",
     "gender": "male",
     "location": "Congo",
     "pic": "images/male.png"},
    {"name": "Kaka Kamissoko",
     "age": "32",
     "gender": "male",
     "location": "Congo",
     "pic": "images/male.png"},
    {"name": "Genicka Hamisi",
     "age": "30",
     "gender": "female",
     "location": "Congo",
     "pic": "images/female.png"},
    {"name": "Burhan Mohammed",
     "age": "20",
     "gender": "male",
     "location": "Syria",
     "pic": "images/male.png"},
    {"name": "Assel Dannourah",
     "age": "29",
     "gender": "female",
     "location": "Syria",
     "pic": "images/female.png"},
    {"name": "Lazim Uri",
     "age": "35",
     "gender": "female",
     "location": "Syria",
     "pic": "images/female.png"},
    {"name": "Shayma Halima",
     "age": "37",
     "gender": "female",
     "location": "Syria",
     "pic": "images/female.png"}
  ];
  $scope.orderList = "name";
}